### ISSUE TITLE
Upgrade the haskell template

### ISSUE THREAD

**Issue by lsmor** [gitpod-io/template-haskell#1]
### The problem
The current template uses the [haskell platform](https://www.haskell.org/platform/), which is deprecated. Also, It relies in stack to build a project using a very old snapshot (resolver - 15)

### The solution
The template should use the new ghcup tool, which enables easy management of the haskell tooling, including the compiler, the language server protocol implementation (a.k.a. hls), and the build tooling. Also, the stackage resolver should be updated

### Pull request

I have prepared a docker file at [upgrade-template](https://github.com/lsmor/template-haskell/tree/upgrade-template) branch in my fork. I can PR it if you accept this proposal.

**Comment by mikevdg** [comment]
I found the same thing and submitted: https://github.com/gitpod-io/template-haskell/pull/2

Your solution is cleaner. You got the language server working better than me. However, out of the box:

```
gitpod /workspace/template-haskell (upgrade-template) $ stack build

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for GitpodTemplate-0.0.0.0:
    base-4.14.3.0 from stack configuration does not match >=4.13.0.0 && <4.14  (latest matching version is 4.13.0.0)
needed since GitpodTemplate is a build target.
```

It looks like one thing is set to use the latest version, and another isn't. I'll have a look.

**Comment by mikevdg** [comment]
Also, I'm thinking it would be nice to have a more comprehensive `stack.yaml` and add a `package.yaml`? I'm not really a stack expert.

**Comment by sagor999** [comment]
@lsmor @mikevdg I would be more then happy to review a PR that addresses this issue. So feel free to open a PR. There is one open already from @mikevdg and looking into why CI is not building it correctly. But if it is obsolete, lets close it and have a new one that does things better(?).
